# Generated by Django 5.2.13 on 2026-04-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/%Y/%m/'),
        ),
    ]
