# Generated by Django 5.2.13 on 2026-04-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='photos/%Y/%m/'),
            preserve_default=False,
        ),
    ]
